### ISSUE TITLE
Unexpected type of JSON object member with key mtls_endpoint_aliases

### ISSUE THREAD

**Issue by jsm174** [jhipster/jhipster-control-center#174]
When trying to launch the control center via `docker-compose`, the following error is displayed: 

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryReactiveClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalArgumentException: Unable to resolve Configuration with the provided Issuer of "http://keycloak:9080/auth/realms/jhipster"
docker-jhipster-control-center-1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
docker-jhipster-control-center-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
docker-jhipster-control-center-1  | 	... 40 common frames omitted
docker-jhipster-control-center-1  | Caused by: java.lang.IllegalArgumentException: Unable to resolve Configuration with the provided Issuer of "http://keycloak:9080/auth/realms/jhipster"
docker-jhipster-control-center-1  | 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:221)
docker-jhipster-control-center-1  | 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.fromIssuerLocation(ClientRegistrations.java:145)
docker-jhipster-control-center-1  | 	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getBuilderFromIssuerIfPossible(OAuth2ClientPropertiesRegistrationAdapter.java:83)
docker-jhipster-control-center-1  | 	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistration(OAuth2ClientPropertiesRegistrationAdapter.java:59)
docker-jhipster-control-center-1  | 	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.lambda$getClientRegistrations$0(OAuth2ClientPropertiesRegistrationAdapter.java:53)
docker-jhipster-control-center-1  | 	at java.base/java.util.HashMap.forEach(Unknown Source)
docker-jhipster-control-center-1  | 	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistrations(OAuth2ClientPropertiesRegistrationAdapter.java:52)
docker-jhipster-control-center-1  | 	at org.springframework.boot.autoconfigure.security.oauth2.client.reactive.ReactiveOAuth2ClientConfigurations$ReactiveClientRegistrationRepositoryConfiguration.clientRegistrationRepository(ReactiveOAuth2ClientConfigurations.java:56)
docker-jhipster-control-center-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
docker-jhipster-control-center-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
docker-jhipster-control-center-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
docker-jhipster-control-center-1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
docker-jhipster-control-center-1  | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
docker-jhipster-control-center-1  | 	... 41 common frames omitted
docker-jhipster-control-center-1  | Caused by: java.lang.RuntimeException: com.nimbusds.oauth2.sdk.ParseException: Unexpected type of JSON object member with key mtls_endpoint_aliases
docker-jhipster-control-center-1  | 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.parse(ClientRegistrations.java:232)
docker-jhipster-control-center-1  | 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.lambda$oidc$0(ClientRegistrations.java:157)
docker-jhipster-control-center-1  | 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:209)
docker-jhipster-control-center-1  | 	... 53 common frames omitted
docker-jhipster-control-center-1  | Caused by: com.nimbusds.oauth2.sdk.ParseException: Unexpected type of JSON object member with key mtls_endpoint_aliases
docker-jhipster-control-center-1  | 	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getGeneric(JSONObjectUtils.java:161)
docker-jhipster-control-center-1  | 	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getJSONObject(JSONObjectUtils.java:827)
docker-jhipster-control-center-1  | 	at com.nimbusds.oauth2.sdk.as.AuthorizationServerMetadata.parse(AuthorizationServerMetadata.java:2042)
docker-jhipster-control-center-1  | 	at com.nimbusds.openid.connect.sdk.op.OIDCProviderMetadata.parse(OIDCProviderMetadata.java:1362)
docker-jhipster-control-center-1  | 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.parse(ClientRegistrations.java:229)
docker-jhipster-control-center-1  | 	... 55 common frames omitted
```

The top of the stack trace is misleading, because I was thinking the container couldn't reach the keycloak container. After adding a delay, connecting, and running curl, it definitely can connect:

```
docker ps
CONTAINER ID   IMAGE                                     COMMAND                   CREATED         STATUS         PORTS                                                                                                NAMES
7970d9c8fa91   jhipster/jhipster-control-center:v0.5.0   "/bin/sh -c 'echo \"`…"   5 seconds ago   Up 4 seconds   127.0.0.1:7419->7419/tcp                                                                             docker-jhipster-control-center-1
79d813a80176   jboss/keycloak:15.0.2                     "/opt/jboss/tools/do…"    6 seconds ago   Up 5 seconds   8080/tcp, 127.0.0.1:9080->9080/tcp, 127.0.0.1:9443->9443/tcp, 8443/tcp, 127.0.0.1:10990->10990/tcp   docker-keycloak-1
➜  ~ docker exec -it 7970d9c8fa91  /bin/bash
root@7970d9c8fa91:/# curl http://keycloak:9080/auth/realms/jhipster
{"realm":"jhipster","public_key":"....","token-service":"http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect","account-service":"http://keycloak:9080/auth/realms/jhipster/account","tokens-not-before":0}
root@7970d9c8fa91:/#
``` 

Further down the stack trace:

```
docker-jhipster-control-center-1  | Caused by: java.lang.RuntimeException: com.nimbusds.oauth2.sdk.ParseException: Unexpected type of JSON object member with key mtls_endpoint_aliases
```

I think this could be similar to: https://github.com/jhipster/generator-jhipster/pull/15836#issuecomment-898940758

**Comment by pascalgrimaud** [comment]
Increasing the bounty

**Comment by DDOUP** [comment]
Is somebody working on it?

**Comment by nassimerrahoui** [comment]
@DDOUP I was working on it but I didn't have time to continue for the moment. You can take the issue if you want ?

**Comment by Walnussbaer** [comment]
The solution is simple. In my case the dependency org.springframework.security.oauth::spring-security-oauth2 imported the dependency com.nimbusds::oauth2-oidc-sdk , but a very old version of it, 6. something. 

I'm not aware of your project structure here, because I just stumbled accross this thread, but if you are using Maven, just do the following: 

Update the version of com.nimbusds::oauth2-oidc-sdk in your <dependencyManagement> tag to version 9.22.2.

Or just import the new version in your <dependencies> tag. 

Then you should be good to go!

**Comment by nassimerrahoui** [comment]
@Walnussbaer Thank you for your help ! I will try your solution. The other thing is that we have to update the whole application to get all JHipster dependencies.

**Comment by Walnussbaer** [comment]
You are welcome, I' curious whether it works out for you too!

**Comment by floreez237** [comment]
@fchiri Tried your answer and it was on spot 
Thank you very much
PLease Jhispter should think about updating image so that it can run as this error prevent the image from running with oauth2

**Comment by ManjunathRNuvepro** [comment]
@Walnussbaer Thanks for the help.

com.nimbusds.oauth2.sdk.ParseException: Unexpected type of JSON object member with key "mtls_endpoint_aliases" this issue is ressolved as I updated the nimbusds to the 9.34

**Comment by kanuwana** [comment]
As Great Thanks! @[Walnussbaer] (https://github.com/Walnussbaer) It worked. 
Simplest solution. 
Update the version of com.nimbusds::oauth2-oidc-sdk in your dependencyManagement tag to version 9.22.2 or higher.

**Comment by MingtaoSun** [comment]
> The problem is in the incompatibility between minbus-jose-jwt 7.1 and the 9.15. Specifically, the call to the json parser in 7.1 is an JsonObject: public JSONObject toJSONObject()
> 
> in 9.15 is a map: public Map<String, Object> toJSONObject()
> 
> So, minbus-jose-jwt 9.15 and spring-security-oauth2-jose 5.2.2.RELEASE are incompatibility.
> 
> The solution is using the the 5.4.5 of spring-security-oauth2-jose.
> 
> Here the dependencies to add to the pom:
> 
> org.springframework.security spring-security-oauth2-jose 5.4.5 com.nimbusds oauth2-oidc-sdk 9.15 runtime

spring-security-oauth2-jose 5.4.5 (https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-jose/5.4.5) depends on nimbus-jose-jwt 8.20.2, in which the `toJSONObject()` method still returns a JSONObject .

spring-security-oauth2-jose 5.5 depends on nimbus-jose-jwt 9.8.1, in which the `toJSONObject()` method returns a Map.

And I recommend com.nimbusds oauth2-oidc-sdk 9.4, which happens to depend on nimbus-jose-jwt 9.8.1 as well.

**Comment by iHateThisGameSo** [comment]
Hi JHipster maintainers. I am looking at #174 and noticed there are already several open, mergeable PRs for the Nimbus/OIDC metadata parsing fix, including #194, #208, and #209.

Before preparing another patch, could you confirm what would be most useful here?

- review/update one of the existing approaches
- prepare a narrower PR with only the dependency pin plus a regression test
- prepare an end-to-end verification against the Keycloak compose setup

I want to avoid adding duplicate noise and can keep the change focused on whatever path you prefer.

**Comment by woahwhattheheck** [comment]
I've opened #227 for this issue. It takes a different angle from the open PRs (#194, #208, #209), so I want to lay out the reasoning and then defer to you on which direction you'd prefer.

The message in the report is raised by `JSONObjectUtils.getGeneric`. That method — and the exact `"Unexpected type of JSON object member with key ..."` string it throws — exists only on the `com.nimbusds:oauth2-oidc-sdk` **7.x** line. It is not present in 8.36, nor in the 9.x releases. So the failing classpath had a 7.x SDK on it.

Tracing where a 7.x SDK can enter this build:

| Managed by | `oauth2-oidc-sdk` | `spring-security` |
| --- | --- | --- |
| `spring-boot-dependencies:2.3.1.RELEASE` | **7.1.1** | 5.3.3.RELEASE |
| `spring-boot-dependencies:2.4.3` / `2.4.4` | 8.36 | 5.4.5 |

`pom.xml` targets the Boot 2.4.x generation — `jhipster-dependencies:7.0.0` inherits from `jhipster-parent:7.0.0`, whose parent is `spring-boot-dependencies:2.4.4`. But the OAuth2 client starter carries an explicit override back to the 2.3.1 generation:

```xml
<oauth2-client.version>2.3.1.RELEASE</oauth2-client.version>
```

That override is the only thing in the file tied to the 7.1.1 generation. #227 removes it (two deleted lines, no additions) so the starter is managed by the imported BOM along with everything else, rather than pinning a transitive Nimbus artifact over the top of it. That's also the direction @fchiri pointed at in this thread — aligning the OAuth2 stack with the rest of the Spring Security version instead of carrying a split one.

It also adds three parsing tests against `OIDCProviderMetadata.parse`, the entry point in the reported stack trace. One of them asserts that `getMtlsEndpointAliases()` actually returns the mTLS endpoints, so the field is verified as parsed and retained rather than only that startup stops throwing. They're pure parsing assertions — no socket, no container.

To be clear, I'm not proposing this to displace the existing PRs, and I'd rather not add noise to an issue that already has several good submissions. If you'd prefer to advance one of those instead, I'm happy to strip #227 down to just the regression test so it can land alongside whichever fix you pick. I can also add a `maven-enforcer-plugin` `bannedDependencies` rule against the `oauth2-oidc-sdk` 7.x range if you want the combination guarded against returning on a future bump.

Two questions when you have a moment:

1. Which approach would you like to take forward — the override removal, or one of the existing pins?
2. Is the `$500` bounty on this issue still open for whichever PR you merge?

Happy to follow up on whatever CI reports.

**Comment by woahwhattheheck** [comment]
I have a reproduction for this, and it explains why it has been awkward to verify.

The trigger is **how** the discovery document reaches Nimbus, not the document itself.
`ClientRegistrations` reads it into a `Map` with Jackson and then calls
`OIDCProviderMetadata.parse(new JSONObject(map))`. That constructor copies only the top level, so
the nested `mtls_endpoint_aliases` value is still a `java.util.LinkedHashMap` rather than a
`net.minidev.json.JSONObject`, and `oauth2-oidc-sdk` 8.36.1 rejects it:

```
Caused by: com.nimbusds.oauth2.sdk.ParseException: Unexpected type: class java.util.LinkedHashMap
```

The practical consequence: parsing the *same* document from a `String` succeeds on every SDK
version I tried, because the SDK's own parser builds `JSONObject` nested members. I checked four
pairings in isolation, feeding each one a document parsed from a String — `oauth2-oidc-sdk` 7.1.1,
8.36.1 and 9.43.6 all parsed it without error. So a test written against the String path passes
with or without a fix. Feeding the same versions the shallow-map shape instead reproduces it:
7.1.1, 8.36.1 with JOSE 8.20.2, and 8.36.1 with JOSE 9.37.3 all throw, while 9.43.6 parses it.

Running that against this project, with only `pom.xml` differing and everything else identical:

| | resolved artifacts | test result |
| --- | --- | --- |
| current `main` | `oauth2-oidc-sdk:8.36.1`, `nimbus-jose-jwt:8.20.2` | Tests run: 3, **Failures: 1, Errors: 1** |
| with the pins | `oauth2-oidc-sdk:9.43.6`, `nimbus-jose-jwt:9.37.3` | Tests run: 3, Failures: 0, Errors: 0 |

The failure on current `main` lands on the same frames as the original report —
`JSONObjectUtils.getGeneric(JSONObjectUtils.java:161)`, `getJSONObject(:827)`,
`AuthorizationServerMetadata.parse(:2042)`.

Two notes that may be useful regardless of which PR you take:

- Pinning `oauth2-oidc-sdk` on its own leaves it on a different generation from
  `nimbus-jose-jwt`, which `spring-boot-dependencies` 2.4.x manages at 8.20.2. 9.43.6 is built
  against the 9.x JOSE line, so I pinned both as a pair.
- `src/main/docker/keycloak.yml` pins `jboss/keycloak:11.0.1`, which predates
  `mtls_endpoint_aliases`. The bundled compose setup therefore does not reproduce the failure,
  which may be part of why this has been hard to confirm locally.

I have updated #227 with the reproducing test and the paired pin. #208 already picks the same
9.43.6 version, so if you would rather advance that one, I am glad to reduce #227 to just the test
so it can land alongside whichever fix you choose — whatever is least work for you.

**Comment by gobountyhunter** [comment]
I'm investigating #174 for the advertised $500 bounty, with AI assistance. I've read the existing work, including #227's HTTP discovery regression. My focus is a separate regression that starts Spring's reactive OAuth2 client auto-configuration and checks creation of the client-registration repository, alongside a minimal dependency fix. I'll verify the failure on the unchanged dependencies before submitting anything.

Could a maintainer confirm that the bounty is still available for an accepted fix? I understand that the existing PRs remain candidates and that this comment does not reserve the reward.

— bountyhunter.1996

**Comment by Pectics** [comment]
Hi maintainers — I reviewed #174 and the discussion of the existing candidate fixes, including #227. Before doing any implementation, could you confirm whether the advertised $500 bounty is still available and whether there is an unmet acceptance requirement that is not already covered by the submitted PRs? I would use AI-assisted development and provide a reproducible failing regression followed by a tested fix. If the current candidates already cover the issue, I will leave this to their authors. I have not started work or reserved the bounty.
